version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Install Spacy Engligh Library
          command: |
            python -m spacy download en_core_web_sm
      - run:
          name: Run Unit tests
          command: |
            python clean_test.py
      - store_test_results:
          path: test-reports


workflows:
  build_and_test:
    jobs:
      - run_tests