version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Download NLTK Data
          command: |
            python -m nltk.downloader stopwords
      - run:
          name: Populate Office Information
          command: |
            python utils.py
  test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - run:
          name: Run Unit tests
          command: |
            mkdir -p test-reports
            pytest --disable-warnings --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build 